
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 15;
  public static final int MENOR = 10;
  public static final int CADENA = 18;
  public static final int INSERTAR = 5;
  public static final int OR = 16;
  public static final int IGUAL = 9;
  public static final int MENORIGUAL = 12;
  public static final int ELIMINAR = 8;
  public static final int PARENTESISCERRADO = 24;
  public static final int FILTRAR = 4;
  public static final int PARENTESISABIERTO = 23;
  public static final int VALORES = 20;
  public static final int ASIGNAR = 7;
  public static final int COMA = 22;
  public static final int ACTUALIZAR = 6;
  public static final int MAYOR = 11;
  public static final int EOF = 0;
  public static final int DIFERENTE = 14;
  public static final int MAYORIGUAL = 13;
  public static final int NUMERO = 19;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 17;
  public static final int PUNTOCOMA = 21;
  public static final int EN = 3;
  public static final int SELECCIONAR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECCIONAR",
  "EN",
  "FILTRAR",
  "INSERTAR",
  "ACTUALIZAR",
  "ASIGNAR",
  "ELIMINAR",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "DIFERENTE",
  "AND",
  "OR",
  "IDENTIFICADOR",
  "CADENA",
  "NUMERO",
  "VALORES",
  "PUNTOCOMA",
  "COMA",
  "PARENTESISABIERTO",
  "PARENTESISCERRADO"
  };
}

